# This is a basic workflow to help you get started with Actions

name: gsalign

# Controls when the action will run. 
on: 
  push:
    branches:
      - 'main'
      - 'dev'
      - 'dev/'
      - '*CI'
      - 'v*'
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run workflow tests
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ["24.04.4"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Install mamba
        run: |
          wget -nv -O Mambaforge.sh https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
          bash Mambaforge.sh -b -p ./mambaforge
          ./mambaforge/bin/mamba init
          source ./mambaforge/etc/profile.d/conda.sh 

      - name: Run pipeline with test data and GSAlign
        run: |
          source ./mambaforge/etc/profile.d/conda.sh
          nextflow run ${GITHUB_WORKSPACE} --aligner gsalign --mamba -profile test,conda
